.TH "mlnlib/mln Directory Reference" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmln_adc\&.h\fP"
.br
.RI "This peripheral is used to measure analog voltages\&. "
.ti -1c
.RI "file \fBmln_common\&.h\fP"
.br
.ti -1c
.RI "file \fBmln_dac\&.h\fP"
.br
.RI "This peripheral is used to generate variable analog voltages for use in other peripherals or on pins\&. "
.ti -1c
.RI "file \fBmln_gpio\&.h\fP"
.br
.RI "This peripheral is used to control the data flow from the pins of the device\&. "
.ti -1c
.RI "file \fBmln_opamp\&.h\fP"
.br
.RI "This peripheral are general purpose opamps which can be configured in various ways, including resistor ladders\&. "
.ti -1c
.RI "file \fBmln_spi\&.h\fP"
.br
.RI "This peripheral is used to communicate with SPI\&. "
.ti -1c
.RI "file \fBmln_timer\&.h\fP"
.br
.ti -1c
.RI "file \fBmln_uart\&.h\fP"
.br
.RI "This peripheral is used to communicate with USART\&. "
.ti -1c
.RI "file \fBmln_vref\&.h\fP"
.br
.RI "This peripheral is used to generate reference voltages for use in other peripherals or on pins\&. "
.ti -1c
.RI "file \fBtester\&.h\fP"
.br
.in -1c
