.TH "mlnlib/main.cpp" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mln/mln_common\&.h'\fP
.br
\fC#include 'mln/mln_opamp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "Main function\&. "
.ti -1c
.RI "\fBISR\fP (PORTA_PORT_vect)"
.br
.RI "Interrupt service routine for PORTA\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmln_gpio\fP \fBbtn_builtin\fP (PA5, \fBMLN_GPIO_DIR_INPUT_PULLUP\fP, true)"
.br
.ti -1c
.RI "\fBmln_gpio\fP \fBled_builtin\fP (PA6, \fBMLN_GPIO_DIR_OUTPUT\fP, true)"
.br
.ti -1c
.RI "\fBmln_opamp_inverting_init_t\fP \fBopamp_init\fP"
.br
.ti -1c
.RI "\fBmln_adc\fP \fBadc\fP (PD2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ISR (PORTA_PORT_vect)"

.PP
Interrupt service routine for PORTA\&. 
.PP
Definition at line \fB112\fP of file \fBmain\&.cpp\fP\&.
.SS "int main (void)"

.PP
Main function\&. 
.PP
\fBReturns\fP
.RS 4
int Should never return 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBmain\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBmln_adc\fP adc(PD2) (PD2)"

.SS "\fBmln_gpio\fP btn_builtin(PA5, \fBMLN_GPIO_DIR_INPUT_PULLUP\fP, true) (PA5, \fBMLN_GPIO_DIR_INPUT_PULLUP\fP, true)"

.SS "\fBmln_gpio\fP led_builtin(PA6, \fBMLN_GPIO_DIR_OUTPUT\fP, true) (PA6, \fBMLN_GPIO_DIR_OUTPUT\fP, true)"

.SS "\fBmln_opamp_inverting_init_t\fP opamp_init"
\fBInitial value:\fP.PP
.nf
= {
    \&.opamp = MLN_OPAMP_DEVICE_0,
    \&.runstdby = false,
    \&.output = true,
    \&.lowpower = false,
    \&.gain = MLN_OPAMP_GAIN_INVERTING_1,
    \&.in_pos = MLN_OPAMP_INVERTING_IN_POS_VDDDIV2,
    \&.in_neg = MLN_OPAMP_INVERTING_IN_NEG_INN
}
.fi

.PP
Definition at line \fB28\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
