.TH "mlnlib/devices/mcp4822.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/devices/mcp4822.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./mln/mln_spi\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmcp4822\fP"
.br
.RI "MCP4822 DAC driver\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMLN_MCP4822_ENABLE_bm\fP   (1 << 4)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmln_mcp4822_gain_t\fP { \fBMLN_MCP4822_GAIN2\fP = 0, \fBMLN_MCP4822_GAIN1\fP }"
.br
.RI "MCP4822 gain enum\&. "
.ti -1c
.RI "enum \fBmln_mcp4822_channel_t\fP { \fBCHANNELA\fP, \fBCHANNELB\fP }"
.br
.RI "MCP4822 channel enum\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MLN_MCP4822_ENABLE_bm   (1 << 4)"

.PP
Definition at line \fB13\fP of file \fBmcp4822\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmln_mcp4822_channel_t\fP"

.PP
MCP4822 channel enum\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICHANNELA \fP\fP
.TP
\fB\fICHANNELB \fP\fP
.PP
Definition at line \fB29\fP of file \fBmcp4822\&.h\fP\&.
.SS "enum \fBmln_mcp4822_gain_t\fP"

.PP
MCP4822 gain enum\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMLN_MCP4822_GAIN2 \fP\fP
.TP
\fB\fIMLN_MCP4822_GAIN1 \fP\fP
.PP
Definition at line \fB19\fP of file \fBmcp4822\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
