.TH "mln_spi" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mln_spi \- SPI peripheral class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mln_spi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmln_spi\fP ()"
.br
.RI "Default \fC\fBmln_spi\fP\fP class initializer\&. "
.ti -1c
.RI "\fBmln_spi\fP (SPI_t *new_spi)"
.br
.RI "Initialize \fC\fBmln_spi\fP\fP class from specific SPI peripheral\&. "
.ti -1c
.RI "\fBmln_spi\fP (SPI_t *new_spi, uint8_t mode)"
.br
.RI "Initialize \fC\fBmln_spi\fP\fP class from specific SPI peripheral and mode\&. "
.ti -1c
.RI "\fBmln_spi\fP (SPI_t *new_spi, \fBmln_pin_t\fP &new_cs)"
.br
.RI "Initialize \fC\fBmln_spi\fP\fP class from specific SPI peripheral and cs pin\&. "
.ti -1c
.RI "\fBmln_spi\fP (SPI_t *new_spi, \fBmln_pin_t\fP &new_cs, const uint8_t mode)"
.br
.RI "Initialize \fC\fBmln_spi\fP\fP class from specific SPI peripheral and cs pin as well as SPI mode\&. "
.ti -1c
.RI "const void \fBexchange\fP (uint8_t *buffer, uint8_t length)"
.br
.RI "Exchange package with SPI peripheral\&. "
.ti -1c
.RI "const void \fBwrite\fP (uint8_t *buffer, uint8_t length)"
.br
.RI "Send package with SPI peripheral\&. "
.ti -1c
.RI "const void \fBread\fP (uint8_t *buffer, uint8_t length)"
.br
.RI "Receive package with SPI peripheral\&. "
.in -1c
.SH "Detailed Description"
.PP 
SPI peripheral class\&. 


.PP
Definition at line \fB50\fP of file \fBmln_spi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mln_spi::mln_spi ()\fC [inline]\fP"

.PP
Default \fC\fBmln_spi\fP\fP class initializer\&. 
.PP
\fBNote\fP
.RS 4
Selects SPI0 as peripheral and no CS pin as well as SPI mode 0 
.RE
.PP

.PP
Definition at line \fB62\fP of file \fBmln_spi\&.h\fP\&.
.SS "mln_spi::mln_spi (SPI_t * new_spi)\fC [inline]\fP"

.PP
Initialize \fC\fBmln_spi\fP\fP class from specific SPI peripheral\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_spi\fP SPI peripheral to use
.RE
.PP
\fBNote\fP
.RS 4
Uses no CS pin as well as SPI mode 0 
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBmln_spi\&.h\fP\&.
.SS "mln_spi::mln_spi (SPI_t * new_spi, uint8_t mode)\fC [inline]\fP"

.PP
Initialize \fC\fBmln_spi\fP\fP class from specific SPI peripheral and mode\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_spi\fP SPI peripheral to use 
.br
\fImode\fP SPI mode to be used (0-3)
.RE
.PP
\fBNote\fP
.RS 4
Uses no CS pin 
.RE
.PP

.PP
Definition at line \fB90\fP of file \fBmln_spi\&.h\fP\&.
.SS "mln_spi::mln_spi (SPI_t * new_spi, \fBmln_pin_t\fP & new_cs)\fC [inline]\fP"

.PP
Initialize \fC\fBmln_spi\fP\fP class from specific SPI peripheral and cs pin\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_spi\fP SPI peripheral to use 
.br
\fInew_cs\fP CS pin to be used
.RE
.PP
\fBNote\fP
.RS 4
Uses SPI mode 0 
.RE
.PP

.PP
Definition at line \fB110\fP of file \fBmln_spi\&.h\fP\&.
.SS "mln_spi::mln_spi (SPI_t * new_spi, \fBmln_pin_t\fP & new_cs, const uint8_t mode)\fC [inline]\fP"

.PP
Initialize \fC\fBmln_spi\fP\fP class from specific SPI peripheral and cs pin as well as SPI mode\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_spi\fP SPI peripheral to use 
.br
\fInew_cs\fP CS pin to bes used 
.br
\fImode\fP SPI mode to be used (0-3) 
.RE
.PP

.PP
Definition at line \fB129\fP of file \fBmln_spi\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const void mln_spi::exchange (uint8_t * buffer, uint8_t length)\fC [inline]\fP"

.PP
Exchange package with SPI peripheral\&. 
.PP
\fBParameters\fP
.RS 4
\fI*buffer\fP Pointer to data buffer to be exchanged 
.br
\fIlength\fP Length of buffer 
.RE
.PP

.PP
Definition at line \fB149\fP of file \fBmln_spi\&.h\fP\&.
.SS "const void mln_spi::read (uint8_t * buffer, uint8_t length)\fC [inline]\fP"

.PP
Receive package with SPI peripheral\&. 
.PP
\fBParameters\fP
.RS 4
\fI*buffer\fP Pointer to data buffer to be received 
.br
\fIlength\fP Length of buffer 
.RE
.PP

.PP
Definition at line \fB193\fP of file \fBmln_spi\&.h\fP\&.
.SS "const void mln_spi::write (uint8_t * buffer, uint8_t length)\fC [inline]\fP"

.PP
Send package with SPI peripheral\&. 
.PP
\fBParameters\fP
.RS 4
\fI*buffer\fP Pointer to data buffer to be sent 
.br
\fIlength\fP Length of buffer 
.RE
.PP

.PP
Definition at line \fB172\fP of file \fBmln_spi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
