.TH "mlnlib/mln/mln_dac.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/mln_dac.h \- This peripheral is used to generate variable analog voltages for use in other peripherals or on pins\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmln_dac\fP"
.br
.RI "DAC peripheral namespace\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmln_dac::config\fP (bool standby, bool buffer)"
.br
.RI "Configure the DAC peripheral\&. "
.ti -1c
.RI "const void \fBmln_dac::enable\fP (void)"
.br
.RI "Enable the DAC peripheral\&. "
.ti -1c
.RI "const void \fBmln_dac::disable\fP (void)"
.br
.RI "Disable the DAC peripheral\&. "
.ti -1c
.RI "const void \fBmln_dac::set\fP (uint16_t value)"
.br
.RI "Set the output of the DAC peripheral\&. "
.in -1c
.SH "Detailed Description"
.PP 
This peripheral is used to generate variable analog voltages for use in other peripherals or on pins\&. 


.PP
\fBAuthor\fP
.RS 4
Cédric Hirschi (cedr02@live.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-27
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBmln_dac\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
