.TH "mln_timer" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mln_timer \- TCA peripheral class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mln_timer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmln_timer\fP (uint16_t period)"
.br
.RI "\fBmln_timer\fP class initializer "
.ti -1c
.RI "void \fBset_isr\fP (void(*f)(void))"
.br
.RI "Set ISR function of TCA peripheral\&. "
.ti -1c
.RI "const void \fBstart\fP (void)"
.br
.RI "Start TCA peripheral\&. "
.ti -1c
.RI "const void \fBstop\fP (void)"
.br
.RI "Stop TCA peripheral\&. "
.ti -1c
.RI "const bool \fBis_running\fP (void)"
.br
.RI "Check if TCA peripheral is running\&. "
.ti -1c
.RI "const float \fBget_period\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBisr\fP )(void)"
.br
.RI "ISR function currently stored in the class\&. "
.in -1c
.SH "Detailed Description"
.PP 
TCA peripheral class\&. 


.PP
Definition at line \fB93\fP of file \fBmln_timer\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mln_timer::mln_timer (uint16_t period)\fC [inline]\fP"

.PP
\fBmln_timer\fP class initializer 
.PP
\fBParameters\fP
.RS 4
\fIperiod\fP Desired period 
.RE
.PP

.PP
Definition at line \fB124\fP of file \fBmln_timer\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const float mln_timer::get_period (void)\fC [inline]\fP"

.PP
Definition at line \fB185\fP of file \fBmln_timer\&.h\fP\&.
.SS "const bool mln_timer::is_running (void)\fC [inline]\fP"

.PP
Check if TCA peripheral is running\&. 
.PP
\fBReturns\fP
.RS 4
Whether TCA peripheral is running 
.RE
.PP
\fBReturn values\fP
.RS 4
\fItrue\fP Peripheral is running 
.br
\fIfalse\fP Peripheral is not running 
.RE
.PP

.PP
Definition at line \fB178\fP of file \fBmln_timer\&.h\fP\&.
.SS "void mln_timer::set_isr (void(*)(void) f)\fC [inline]\fP"

.PP
Set ISR function of TCA peripheral\&. 
.PP
Definition at line \fB148\fP of file \fBmln_timer\&.h\fP\&.
.SS "const void mln_timer::start (void)\fC [inline]\fP"

.PP
Start TCA peripheral\&. 
.PP
Definition at line \fB163\fP of file \fBmln_timer\&.h\fP\&.
.SS "const void mln_timer::stop (void)\fC [inline]\fP"

.PP
Stop TCA peripheral\&. 
.PP
Definition at line \fB168\fP of file \fBmln_timer\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void(* mln_timer::isr) (void)"

.PP
ISR function currently stored in the class\&. 
.PP
Definition at line \fB104\fP of file \fBmln_timer\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
