.TH "mln_vref" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mln_vref \- Voltage reference peripheral namespace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const void \fBset\fP (\fBMLN_VREF_SEL_t\fP dac=\fBMLN_VREF_2V048\fP, \fBMLN_VREF_SEL_t\fP adc=\fBMLN_VREF_2V048\fP, \fBMLN_VREF_SEL_t\fP ac=\fBMLN_VREF_2V048\fP, bool standby=false)"
.br
.RI "Configure and set voltages of the VREF peripheral\&. "
.in -1c
.SH "Detailed Description"
.PP 
Voltage reference peripheral namespace\&. 


.SH "Function Documentation"
.PP 
.SS "const void mln_vref::set (\fBMLN_VREF_SEL_t\fP dac = \fC\fBMLN_VREF_2V048\fP\fP, \fBMLN_VREF_SEL_t\fP adc = \fC\fBMLN_VREF_2V048\fP\fP, \fBMLN_VREF_SEL_t\fP ac = \fC\fBMLN_VREF_2V048\fP\fP, bool standby = \fCfalse\fP)\fC [inline]\fP"

.PP
Configure and set voltages of the VREF peripheral\&. 
.PP
\fBParameters\fP
.RS 4
\fIdac\fP Reference voltage of DAC peripheral to set 
.br
\fIadc\fP Reference voltage of ADC peripheral to set 
.br
\fIac\fP Reference voltage of AC peripheral to set 
.br
\fIstandby\fP If true, the peripheral is also running in device standby 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBmln_vref\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
