.TH "mlnlib/mln/mln_timer.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/mln_timer.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <avr/io\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmln_timer\fP"
.br
.RI "TCA peripheral class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMLN_TIMER_DIV\fP   (F_CPU / 1000000UL)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBMLN_TIMER_GET_DIV\fP (uint32_t period)"
.br
.RI "Helper function to get the lowest possible clock division to get certain period\&. "
.ti -1c
.RI "\fBISR\fP (TCA0_OVF_vect)"
.br
.RI "Standard ISR for TCA0\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmln_timer\fP * \fBtimer0_isr\fP"
.br
.ti -1c
.RI "const uint16_t \fBmln_timer_divs\fP [] = {1, 2, 4, 8, 16, 64, 256, 1024}"
.br
.RI "Available clock dividers in the TCA peripheral in numerical form\&. "
.ti -1c
.RI "uint32_t \fBmln_timer_max_periods\fP [] = {65, 131, 262, 524, 1048, 4194, 16776, 67107}"
.br
.RI "The maximum periods achievable by clock division, in ms at 1MHz\&. "
.ti -1c
.RI "const TCA_SINGLE_CLKSEL_t \fBmln_timer_divs_bm\fP []"
.br
.RI "Available clock dividers in the TCA peripheral as bitmasks\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MLN_TIMER_DIV   (F_CPU / 1000000UL)"

.PP
Definition at line \fB20\fP of file \fBmln_timer\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "ISR (TCA0_OVF_vect)"

.PP
Standard ISR for TCA0\&. 
.PP
\fBNote\fP
.RS 4
Does nothing but reset the corresponding flag 
.RE
.PP

.PP
Definition at line \fB194\fP of file \fBmln_timer\&.h\fP\&.
.SS "uint8_t MLN_TIMER_GET_DIV (uint32_t period)"

.PP
Helper function to get the lowest possible clock division to get certain period\&. 
.PP
\fBParameters\fP
.RS 4
\fIperiod\fP Required period
.RE
.PP
\fBReturns\fP
.RS 4
Index for \fCmln_timer_\&.\&.\&.\fP arrays 
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBmln_timer\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const uint16_t mln_timer_divs[] = {1, 2, 4, 8, 16, 64, 256, 1024}"

.PP
Available clock dividers in the TCA peripheral in numerical form\&. 
.PP
Definition at line \fB42\fP of file \fBmln_timer\&.h\fP\&.
.SS "const TCA_SINGLE_CLKSEL_t mln_timer_divs_bm[]"
\fBInitial value:\fP.PP
.nf
= {
    TCA_SINGLE_CLKSEL_DIV1_gc,
    TCA_SINGLE_CLKSEL_DIV2_gc,
    TCA_SINGLE_CLKSEL_DIV4_gc,
    TCA_SINGLE_CLKSEL_DIV8_gc,
    TCA_SINGLE_CLKSEL_DIV16_gc,
    TCA_SINGLE_CLKSEL_DIV64_gc,
    TCA_SINGLE_CLKSEL_DIV256_gc,
    TCA_SINGLE_CLKSEL_DIV1024_gc
}
.fi

.PP
Available clock dividers in the TCA peripheral as bitmasks\&. 
.PP
Definition at line \fB52\fP of file \fBmln_timer\&.h\fP\&.
.SS "uint32_t mln_timer_max_periods[] = {65, 131, 262, 524, 1048, 4194, 16776, 67107}"

.PP
The maximum periods achievable by clock division, in ms at 1MHz\&. 
.PP
Definition at line \fB47\fP of file \fBmln_timer\&.h\fP\&.
.SS "\fBmln_timer\fP* timer0_isr"

.PP
Definition at line \fB32\fP of file \fBmln_timer\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
