.TH "mlnlib/mln/mln_common.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/mln_common.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <avr/io\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include 'mln_gpio\&.h'\fP
.br
\fC#include 'mln_uart\&.h'\fP
.br
\fC#include 'mln_timer\&.h'\fP
.br
\fC#include 'mln_vref\&.h'\fP
.br
\fC#include 'mln_adc\&.h'\fP
.br
\fC#include 'mln_dac\&.h'\fP
.br
\fC#include 'mln_spi\&.h'\fP
.br
\fC#include '\&.\&./devices/mcp4822\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmln_init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mln_init (void)"

.PP
Definition at line \fB27\fP of file \fBmln_common\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
