.TH "mlnlib/mln/mln_gpio.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/mln_gpio.h \- This peripheral is used to control the data flow from the pins of the device\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmln_pin_t\fP"
.br
.RI "Standard pin struct\&. "
.ti -1c
.RI "class \fBmln_gpio\fP"
.br
.RI "GPIO peripheral class\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmln_gpio_dir_t\fP { \fBMLN_GPIO_DIR_OUTPUT\fP = 0, \fBMLN_GPIO_DIR_INPUT\fP, \fBMLN_GPIO_DIR_INPUT_PULLUP\fP }"
.br
.RI "Pin direction enum\&. "
.ti -1c
.RI "enum \fBmln_gpio_isc_t\fP { \fBMLN_GPIO_ISC_DISABLED\fP = 0, \fBMLN_GPIO_ISC_BOTHEDGES\fP, \fBMLN_GPIO_ISC_RISING\fP, \fBMLN_GPIO_ISC_FALLING\fP, \fBMLN_GPIO_ISC_LOWLEVEL\fP = 5 }"
.br
.RI "Pin interrupt type enum\&. "
.in -1c
.SH "Detailed Description"
.PP 
This peripheral is used to control the data flow from the pins of the device\&. 


.PP
\fBAuthor\fP
.RS 4
Cédric Hirschi (cedr02@live.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-27
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBmln_gpio\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmln_gpio_dir_t\fP"

.PP
Pin direction enum\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMLN_GPIO_DIR_OUTPUT \fP\fP
.TP
\fB\fIMLN_GPIO_DIR_INPUT \fP\fP
.TP
\fB\fIMLN_GPIO_DIR_INPUT_PULLUP \fP\fP
.PP
Definition at line \fB108\fP of file \fBmln_gpio\&.h\fP\&.
.SS "enum \fBmln_gpio_isc_t\fP"

.PP
Pin interrupt type enum\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMLN_GPIO_ISC_DISABLED \fP\fP
.TP
\fB\fIMLN_GPIO_ISC_BOTHEDGES \fP\fP
.TP
\fB\fIMLN_GPIO_ISC_RISING \fP\fP
.TP
\fB\fIMLN_GPIO_ISC_FALLING \fP\fP
.TP
\fB\fIMLN_GPIO_ISC_LOWLEVEL \fP\fP
.PP
Definition at line \fB119\fP of file \fBmln_gpio\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
