.TH "mln_opamp" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mln_opamp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mln_opamp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmln_opamp\fP ()=default"
.br
.ti -1c
.RI "\fBmln_opamp\fP (\fBOPAMP_SETUP_t\fP *new_setup)"
.br
.ti -1c
.RI "bool \fBhas_settled\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB121\fP of file \fBmln_opamp\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mln_opamp::mln_opamp ()\fC [default]\fP"

.SS "mln_opamp::mln_opamp (\fBOPAMP_SETUP_t\fP * new_setup)\fC [inline]\fP"

.PP
Definition at line \fB329\fP of file \fBmln_opamp\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool mln_opamp::has_settled (void)\fC [inline]\fP"

.PP
Definition at line \fB368\fP of file \fBmln_opamp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
