.TH "mln_pin_t" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mln_pin_t \- Standard pin struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mln_gpio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "volatile PORT_t * \fBport\fP"
.br
.ti -1c
.RI "uint8_t \fBpin_num\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Standard pin struct\&. 


.PP
Definition at line \fB98\fP of file \fBmln_gpio\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t mln_pin_t::pin_num"

.PP
Definition at line \fB101\fP of file \fBmln_gpio\&.h\fP\&.
.SS "volatile PORT_t* mln_pin_t::port"

.PP
Definition at line \fB100\fP of file \fBmln_gpio\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
