.TH "mlnlib/mln/mln_gpio.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/mln_gpio.h
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPIN_t\fP"
.br
.ti -1c
.RI "class \fBmln_gpio\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPIN_DIR_t\fP { \fBOUTPUT\fP, \fBINPUT\fP, \fBINPUT_PULLUP\fP }"
.br
.ti -1c
.RI "enum \fBPIN_ISC_t\fP { \fBDISABLED\fP, \fBBOTHEDGES\fP, \fBRISING\fP, \fBFALLING\fP, \fBLOWLEVEL\fP = 5 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPIN_DIR_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOUTPUT \fP\fP
.TP
\fB\fIINPUT \fP\fP
.TP
\fB\fIINPUT_PULLUP \fP\fP
.PP
Definition at line \fB99\fP of file \fBmln_gpio\&.h\fP\&.
.SS "enum \fBPIN_ISC_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDISABLED \fP\fP
.TP
\fB\fIBOTHEDGES \fP\fP
.TP
\fB\fIRISING \fP\fP
.TP
\fB\fIFALLING \fP\fP
.TP
\fB\fILOWLEVEL \fP\fP
.PP
Definition at line \fB106\fP of file \fBmln_gpio\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
