.TH "mlnlib/mln/mln_uart.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/mln_uart.h \- This peripheral is used to communicate with USART\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include 'mln_gpio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmln_uart\fP"
.br
.RI "USART peripheral class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMLN_UART_BUF_SIZE\fP   32"
.br
.RI "Maximum UART buffer size\&. "
.ti -1c
.RI "#define \fBMLN_UART0_PIN_TX\fP   PA0"
.br
.ti -1c
.RI "#define \fBMLN_UART0_PIN_RX\fP   PA1"
.br
.ti -1c
.RI "#define \fBMLN_UART1_PIN_TX\fP   PC0"
.br
.ti -1c
.RI "#define \fBMLN_UART1_PIN_RX\fP   PC1"
.br
.ti -1c
.RI "#define \fBMLN_UART2_PIN_TX\fP   PF0"
.br
.ti -1c
.RI "#define \fBMLN_UART2_PIN_RX\fP   PF1"
.br
.ti -1c
.RI "#define \fBMLN_UART_NUM_INSTS\fP   3"
.br
.ti -1c
.RI "#define \fBMLN_UART_BAUD_NUM\fP(BAUD)   ((float)(F_CPU * 64 / (16 * (float)BAUD)) + 0\&.5)"
.br
.RI "Macro to calculate register value from baud rate\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmln_uart_stream_write\fP (char character, FILE *f)"
.br
.RI "Helper function to write from std stream to USART peripheral\&. "
.ti -1c
.RI "int \fBmln_uart_stream_read\fP (FILE *f)"
.br
.RI "Helper function to read USART peripheral to std stream\&. "
.ti -1c
.RI "\fBISR\fP (USART3_RXC_vect)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmln_uart\fP * \fBmln_uart_stream_uart\fP"
.br
.RI "USART stream (for printf functionality) "
.in -1c
.SH "Detailed Description"
.PP 
This peripheral is used to communicate with USART\&. 


.PP
\fBAuthor\fP
.RS 4
Cédric Hirschi (cedr02@live.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-27
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBmln_uart\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MLN_UART0_PIN_RX   PA1"

.PP
Definition at line \fB36\fP of file \fBmln_uart\&.h\fP\&.
.SS "#define MLN_UART0_PIN_TX   PA0"

.PP
Definition at line \fB35\fP of file \fBmln_uart\&.h\fP\&.
.SS "#define MLN_UART1_PIN_RX   PC1"

.PP
Definition at line \fB38\fP of file \fBmln_uart\&.h\fP\&.
.SS "#define MLN_UART1_PIN_TX   PC0"

.PP
Definition at line \fB37\fP of file \fBmln_uart\&.h\fP\&.
.SS "#define MLN_UART2_PIN_RX   PF1"

.PP
Definition at line \fB40\fP of file \fBmln_uart\&.h\fP\&.
.SS "#define MLN_UART2_PIN_TX   PF0"

.PP
Definition at line \fB39\fP of file \fBmln_uart\&.h\fP\&.
.SS "#define MLN_UART_BAUD_NUM(BAUD)   ((float)(F_CPU * 64 / (16 * (float)BAUD)) + 0\&.5)"

.PP
Macro to calculate register value from baud rate\&. 
.PP
Definition at line \fB70\fP of file \fBmln_uart\&.h\fP\&.
.SS "#define MLN_UART_BUF_SIZE   32"

.PP
Maximum UART buffer size\&. 
.PP
\fBNote\fP
.RS 4
Currently RX only 
.PP
Can be changed without further problems 
.RE
.PP

.PP
Definition at line \fB33\fP of file \fBmln_uart\&.h\fP\&.
.SS "#define MLN_UART_NUM_INSTS   3"

.PP
Definition at line \fB63\fP of file \fBmln_uart\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "ISR (USART3_RXC_vect)"

.PP
Definition at line \fB277\fP of file \fBmln_uart\&.h\fP\&.
.SS "int mln_uart_stream_read (FILE * f)"

.PP
Helper function to read USART peripheral to std stream\&. 
.PP
Definition at line \fB272\fP of file \fBmln_uart\&.h\fP\&.
.SS "int mln_uart_stream_write (char character, FILE * f)"

.PP
Helper function to write from std stream to USART peripheral\&. 
.PP
Definition at line \fB266\fP of file \fBmln_uart\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBmln_uart\fP* mln_uart_stream_uart"

.PP
USART stream (for printf functionality) 
.PP
Definition at line \fB82\fP of file \fBmln_uart\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
