.TH "mlnlib/mln/mln_spi.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/mln_spi.h \- This peripheral is used to communicate with SPI\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include 'mln_gpio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmln_spi\fP"
.br
.RI "SPI peripheral class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMLN_SPI_BUF_SIZE\fP   32"
.br
.RI "Maximum SPI buffer size\&. "
.ti -1c
.RI "#define \fBMLN_SPI0_PIN_MOSI\fP   PA4"
.br
.ti -1c
.RI "#define \fBMLN_SPI0_PIN_MISO\fP   PA5"
.br
.ti -1c
.RI "#define \fBMLN_SPI0_PIN_SCK\fP   PA6"
.br
.ti -1c
.RI "#define \fBMLN_SPI0_PIN_SS\fP   PA7"
.br
.ti -1c
.RI "#define \fBMLN_SPI1_PIN_MOSI\fP   PC0"
.br
.ti -1c
.RI "#define \fBMLN_SPI1_PIN_MISO\fP   PC1"
.br
.ti -1c
.RI "#define \fBMLN_SPI1_PIN_SCK\fP   PC2"
.br
.ti -1c
.RI "#define \fBMLN_SPI1_PIN_SS\fP   PC3"
.br
.ti -1c
.RI "#define \fBMLN_SPI_CLKSEL\fP   (SPI_CLK2X_bm)"
.br
.RI "SPI peripheral speed bitmaps\&. "
.in -1c
.SH "Detailed Description"
.PP 
This peripheral is used to communicate with SPI\&. 


.PP
\fBAuthor\fP
.RS 4
Cédric Hirschi (cedr02@live.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-27
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBmln_spi\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MLN_SPI0_PIN_MISO   PA5"

.PP
Definition at line \fB29\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI0_PIN_MOSI   PA4"

.PP
Definition at line \fB28\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI0_PIN_SCK   PA6"

.PP
Definition at line \fB30\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI0_PIN_SS   PA7"

.PP
Definition at line \fB31\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI1_PIN_MISO   PC1"

.PP
Definition at line \fB34\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI1_PIN_MOSI   PC0"

.PP
Definition at line \fB33\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI1_PIN_SCK   PC2"

.PP
Definition at line \fB35\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI1_PIN_SS   PC3"

.PP
Definition at line \fB36\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI_BUF_SIZE   32"

.PP
Maximum SPI buffer size\&. 
.PP
\fBNote\fP
.RS 4
Currently RX only 
.PP
Can be changed without further problems 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI_CLKSEL   (SPI_CLK2X_bm)"

.PP
SPI peripheral speed bitmaps\&. 
.PP
\fBNote\fP
.RS 4
Can be changed without further problems 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBmln_spi\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
