.TH "mlnlib/mln/mln_spi.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/mln_spi.h
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include 'mln_gpio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmln_spi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMLN_SPI_BUF_SIZE\fP   32"
.br
.ti -1c
.RI "#define \fBMLN_SPI0_PIN_MOSI\fP   PA4"
.br
.ti -1c
.RI "#define \fBMLN_SPI0_PIN_MISO\fP   PA5"
.br
.ti -1c
.RI "#define \fBMLN_SPI0_PIN_SCK\fP   PA6"
.br
.ti -1c
.RI "#define \fBMLN_SPI0_PIN_SS\fP   PA7"
.br
.ti -1c
.RI "#define \fBMLN_SPI1_PIN_MOSI\fP   PC0"
.br
.ti -1c
.RI "#define \fBMLN_SPI1_PIN_MISO\fP   PC1"
.br
.ti -1c
.RI "#define \fBMLN_SPI1_PIN_SCK\fP   PC2"
.br
.ti -1c
.RI "#define \fBMLN_SPI1_PIN_SS\fP   PC3"
.br
.ti -1c
.RI "#define \fBMLN_SPI_CLKSEL\fP   (SPI_CLK2X_bm)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MLN_SPI0_PIN_MISO   PA5"

.PP
Definition at line \fB18\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI0_PIN_MOSI   PA4"

.PP
Definition at line \fB17\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI0_PIN_SCK   PA6"

.PP
Definition at line \fB19\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI0_PIN_SS   PA7"

.PP
Definition at line \fB20\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI1_PIN_MISO   PC1"

.PP
Definition at line \fB23\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI1_PIN_MOSI   PC0"

.PP
Definition at line \fB22\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI1_PIN_SCK   PC2"

.PP
Definition at line \fB24\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI1_PIN_SS   PC3"

.PP
Definition at line \fB25\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI_BUF_SIZE   32"

.PP
Definition at line \fB15\fP of file \fBmln_spi\&.h\fP\&.
.SS "#define MLN_SPI_CLKSEL   (SPI_CLK2X_bm)"

.PP
Definition at line \fB27\fP of file \fBmln_spi\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
