.TH "mln_uart" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mln_uart
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mln_uart\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmln_uart\fP (\fBUART_t\fP new_inst, uint32_t baud)"
.br
.ti -1c
.RI "void \fBset_isr\fP (void(*new_isr)(void))"
.br
.ti -1c
.RI "const void \fBwrite\fP (const uint8_t data)"
.br
.ti -1c
.RI "const uint8_t \fBread\fP (void)"
.br
.ti -1c
.RI "void \fBpush\fP (void)"
.br
.ti -1c
.RI "uint8_t \fBpull\fP (uint8_t *new_buffer)"
.br
.ti -1c
.RI "const bool \fBis_busy_tx\fP (void)"
.br
.ti -1c
.RI "const bool \fBis_busy_rx\fP (void)"
.br
.ti -1c
.RI "const uint8_t \fBdata_available\fP (void)"
.br
.ti -1c
.RI "const void \fBrun_isr\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB117\fP of file \fBmln_uart\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mln_uart::mln_uart (\fBUART_t\fP new_inst, uint32_t baud)\fC [inline]\fP"

.PP
Definition at line \fB180\fP of file \fBmln_uart\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const uint8_t mln_uart::data_available (void)\fC [inline]\fP"

.PP
Definition at line \fB268\fP of file \fBmln_uart\&.h\fP\&.
.SS "const bool mln_uart::is_busy_rx (void)\fC [inline]\fP"

.PP
Definition at line \fB262\fP of file \fBmln_uart\&.h\fP\&.
.SS "const bool mln_uart::is_busy_tx (void)\fC [inline]\fP"

.PP
Definition at line \fB256\fP of file \fBmln_uart\&.h\fP\&.
.SS "uint8_t mln_uart::pull (uint8_t * new_buffer)\fC [inline]\fP"

.PP
Definition at line \fB240\fP of file \fBmln_uart\&.h\fP\&.
.SS "void mln_uart::push (void)\fC [inline]\fP"

.PP
Definition at line \fB228\fP of file \fBmln_uart\&.h\fP\&.
.SS "const uint8_t mln_uart::read (void)\fC [inline]\fP"

.PP
Definition at line \fB218\fP of file \fBmln_uart\&.h\fP\&.
.SS "const void mln_uart::run_isr (void)\fC [inline]\fP"

.PP
Definition at line \fB273\fP of file \fBmln_uart\&.h\fP\&.
.SS "void mln_uart::set_isr (void(*)(void) new_isr)\fC [inline]\fP"

.PP
Definition at line \fB204\fP of file \fBmln_uart\&.h\fP\&.
.SS "const void mln_uart::write (const uint8_t data)\fC [inline]\fP"

.PP
Definition at line \fB209\fP of file \fBmln_uart\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
