.TH "OPA_SETUP" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPA_SETUP
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBOPA_SETUP::CONFIG_e\fP \fBCONFIG_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::GAIN_NONINV_e\fP \fBGAIN_NONINV_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::GAIN_INV_e\fP \fBGAIN_INV_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::PIN_e\fP \fBPIN_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::MUX_e\fP \fBMUX_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::MUXNEG_IN_e\fP \fBMUXNEG_IN_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::MUXPOS_IN_e\fP \fBMUXPOS_IN_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::MUXTOP_IN_e\fP \fBMUXTOP_IN_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::MUXBOT_IN_e\fP \fBMUXBOT_IN_t\fP"
.br
.ti -1c
.RI "typedef enum \fBOPA_SETUP::MUXWIP_IN_e\fP \fBMUXWIP_IN_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCONFIG_e\fP { \fBTOPINS\fP, \fBFOLLOWER\fP, \fBNONINV\fP, \fBINV\fP }"
.br
.ti -1c
.RI "enum \fBGAIN_NONINV_e\fP { \fBGAIN_1_06\fP, \fBGAIN_1_14\fP, \fBGAIN_1_33\fP, \fBGAIN_2\fP, \fBGAIN_2_67\fP, \fBGAIN_4\fP, \fBGAIN_8\fP, \fBGAIN_16\fP }"
.br
.ti -1c
.RI "enum \fBGAIN_INV_e\fP { \fBGAIN_INV_0_06\fP, \fBGAIN_INV_0_14\fP, \fBGAIN_INV_0_33\fP, \fBGAIN_INV_1\fP, \fBGAIN_INV_1_67\fP, \fBGAIN_INV_3\fP, \fBGAIN_INV_7\fP, \fBGAIN_INV_15\fP }"
.br
.ti -1c
.RI "enum \fBPIN_e\fP { \fBPIN_INN\fP, \fBPIN_INP\fP, \fBPIN_OUT\fP }"
.br
.ti -1c
.RI "enum \fBMUX_e\fP { \fBMUXNEG\fP, \fBMUXPOS\fP, \fBMUXTOP\fP, \fBMUXBOT\fP, \fBMUXWIP\fP }"
.br
.ti -1c
.RI "enum \fBMUXNEG_IN_e\fP { \fBMUXNEG_INN\fP, \fBMUXNEG_WIP\fP, \fBMUXNEG_OUT\fP, \fBMUXNEG_DAC\fP }"
.br
.ti -1c
.RI "enum \fBMUXPOS_IN_e\fP { \fBMUXPOS_INP\fP, \fBMUXPOS_WIP\fP, \fBMUXPOS_DAC\fP, \fBMUXPOS_GND\fP, \fBMUXPOS_VDDDIV2\fP, \fBMUXPOS_LINKOUT\fP, \fBMUXPOS_LINKWIP\fP }"
.br
.ti -1c
.RI "enum \fBMUXTOP_IN_e\fP { \fBMUXTOP_OFF\fP, \fBMUXTOP_OUT\fP, \fBMUXTOP_VDD\fP }"
.br
.ti -1c
.RI "enum \fBMUXBOT_IN_e\fP { \fBMUXBOT_OFF\fP, \fBMUXBOT_INP\fP, \fBMUXBOT_INN\fP, \fBMUXBOT_DAC\fP, \fBMUXBOT_LINKOUT\fP, \fBMUXBOT_GND\fP }"
.br
.ti -1c
.RI "enum \fBMUXWIP_IN_e\fP { \fBMUXWIP_WIP0\fP, \fBMUXWIP_WIP1\fP, \fBMUXWIP_WIP2\fP, \fBMUXWIP_WIP3\fP, \fBMUXWIP_WIP4\fP, \fBMUXWIP_WIP5\fP, \fBMUXWIP_WIP6\fP, \fBMUXWIP_WIP7\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBOPA_SETUP::CONFIG_e\fP \fBOPA_SETUP::CONFIG_t\fP"

.SS "typedef enum \fBOPA_SETUP::GAIN_INV_e\fP \fBOPA_SETUP::GAIN_INV_t\fP"

.SS "typedef enum \fBOPA_SETUP::GAIN_NONINV_e\fP \fBOPA_SETUP::GAIN_NONINV_t\fP"

.SS "typedef enum \fBOPA_SETUP::MUX_e\fP \fBOPA_SETUP::MUX_t\fP"

.SS "typedef enum \fBOPA_SETUP::MUXBOT_IN_e\fP \fBOPA_SETUP::MUXBOT_IN_t\fP"

.SS "typedef enum \fBOPA_SETUP::MUXNEG_IN_e\fP \fBOPA_SETUP::MUXNEG_IN_t\fP"

.SS "typedef enum \fBOPA_SETUP::MUXPOS_IN_e\fP \fBOPA_SETUP::MUXPOS_IN_t\fP"

.SS "typedef enum \fBOPA_SETUP::MUXTOP_IN_e\fP \fBOPA_SETUP::MUXTOP_IN_t\fP"

.SS "typedef enum \fBOPA_SETUP::MUXWIP_IN_e\fP \fBOPA_SETUP::MUXWIP_IN_t\fP"

.SS "typedef enum \fBOPA_SETUP::PIN_e\fP \fBOPA_SETUP::PIN_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBOPA_SETUP::CONFIG_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITOPINS \fP\fP
.TP
\fB\fIFOLLOWER \fP\fP
.TP
\fB\fINONINV \fP\fP
.TP
\fB\fIINV \fP\fP
.PP
Definition at line \fB8\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::GAIN_INV_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGAIN_INV_0_06 \fP\fP
.TP
\fB\fIGAIN_INV_0_14 \fP\fP
.TP
\fB\fIGAIN_INV_0_33 \fP\fP
.TP
\fB\fIGAIN_INV_1 \fP\fP
.TP
\fB\fIGAIN_INV_1_67 \fP\fP
.TP
\fB\fIGAIN_INV_3 \fP\fP
.TP
\fB\fIGAIN_INV_7 \fP\fP
.TP
\fB\fIGAIN_INV_15 \fP\fP
.PP
Definition at line \fB28\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::GAIN_NONINV_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGAIN_1_06 \fP\fP
.TP
\fB\fIGAIN_1_14 \fP\fP
.TP
\fB\fIGAIN_1_33 \fP\fP
.TP
\fB\fIGAIN_2 \fP\fP
.TP
\fB\fIGAIN_2_67 \fP\fP
.TP
\fB\fIGAIN_4 \fP\fP
.TP
\fB\fIGAIN_8 \fP\fP
.TP
\fB\fIGAIN_16 \fP\fP
.PP
Definition at line \fB16\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::MUX_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMUXNEG \fP\fP
.TP
\fB\fIMUXPOS \fP\fP
.TP
\fB\fIMUXTOP \fP\fP
.TP
\fB\fIMUXBOT \fP\fP
.TP
\fB\fIMUXWIP \fP\fP
.PP
Definition at line \fB47\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::MUXBOT_IN_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMUXBOT_OFF \fP\fP
.TP
\fB\fIMUXBOT_INP \fP\fP
.TP
\fB\fIMUXBOT_INN \fP\fP
.TP
\fB\fIMUXBOT_DAC \fP\fP
.TP
\fB\fIMUXBOT_LINKOUT \fP\fP
.TP
\fB\fIMUXBOT_GND \fP\fP
.PP
Definition at line \fB82\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::MUXNEG_IN_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMUXNEG_INN \fP\fP
.TP
\fB\fIMUXNEG_WIP \fP\fP
.TP
\fB\fIMUXNEG_OUT \fP\fP
.TP
\fB\fIMUXNEG_DAC \fP\fP
.PP
Definition at line \fB56\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::MUXPOS_IN_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMUXPOS_INP \fP\fP
.TP
\fB\fIMUXPOS_WIP \fP\fP
.TP
\fB\fIMUXPOS_DAC \fP\fP
.TP
\fB\fIMUXPOS_GND \fP\fP
.TP
\fB\fIMUXPOS_VDDDIV2 \fP\fP
.TP
\fB\fIMUXPOS_LINKOUT \fP\fP
.TP
\fB\fIMUXPOS_LINKWIP \fP\fP
.PP
Definition at line \fB64\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::MUXTOP_IN_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMUXTOP_OFF \fP\fP
.TP
\fB\fIMUXTOP_OUT \fP\fP
.TP
\fB\fIMUXTOP_VDD \fP\fP
.PP
Definition at line \fB75\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::MUXWIP_IN_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMUXWIP_WIP0 \fP\fP
.TP
\fB\fIMUXWIP_WIP1 \fP\fP
.TP
\fB\fIMUXWIP_WIP2 \fP\fP
.TP
\fB\fIMUXWIP_WIP3 \fP\fP
.TP
\fB\fIMUXWIP_WIP4 \fP\fP
.TP
\fB\fIMUXWIP_WIP5 \fP\fP
.TP
\fB\fIMUXWIP_WIP6 \fP\fP
.TP
\fB\fIMUXWIP_WIP7 \fP\fP
.PP
Definition at line \fB92\fP of file \fBmln_opamp\&.h\fP\&.
.SS "enum \fBOPA_SETUP::PIN_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPIN_INN \fP\fP
.TP
\fB\fIPIN_INP \fP\fP
.TP
\fB\fIPIN_OUT \fP\fP
.PP
Definition at line \fB40\fP of file \fBmln_opamp\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
