.TH "OPAMP_SETUP_s" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPAMP_SETUP_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mln_opamp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBopamp_n\fP = 0"
.br
.ti -1c
.RI "\fBOPA_SETUP::CONFIG_t\fP \fBconfig\fP = \fBOPA_SETUP::TOPINS\fP"
.br
.ti -1c
.RI "\fBOPA_SETUP::GAIN_INV_t\fP \fBgain_inv\fP = \fBOPA_SETUP::GAIN_INV_0_06\fP"
.br
.ti -1c
.RI "\fBOPA_SETUP::GAIN_NONINV_t\fP \fBgain_noninv\fP = \fBOPA_SETUP::GAIN_1_06\fP"
.br
.ti -1c
.RI "\fBOPA_SETUP::MUXPOS_IN_t\fP \fBpin_pos\fP = \fBOPA_SETUP::MUXPOS_INP\fP"
.br
.ti -1c
.RI "\fBOPA_SETUP::MUXNEG_IN_t\fP \fBpin_neg\fP = \fBOPA_SETUP::MUXNEG_INN\fP"
.br
.ti -1c
.RI "bool \fBrun_in_standby\fP = false"
.br
.ti -1c
.RI "bool \fBoutput\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB105\fP of file \fBmln_opamp\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBOPA_SETUP::CONFIG_t\fP OPAMP_SETUP_s::config = \fBOPA_SETUP::TOPINS\fP"

.PP
Definition at line \fB109\fP of file \fBmln_opamp\&.h\fP\&.
.SS "\fBOPA_SETUP::GAIN_INV_t\fP OPAMP_SETUP_s::gain_inv = \fBOPA_SETUP::GAIN_INV_0_06\fP"

.PP
Definition at line \fB111\fP of file \fBmln_opamp\&.h\fP\&.
.SS "\fBOPA_SETUP::GAIN_NONINV_t\fP OPAMP_SETUP_s::gain_noninv = \fBOPA_SETUP::GAIN_1_06\fP"

.PP
Definition at line \fB112\fP of file \fBmln_opamp\&.h\fP\&.
.SS "uint8_t OPAMP_SETUP_s::opamp_n = 0"

.PP
Definition at line \fB107\fP of file \fBmln_opamp\&.h\fP\&.
.SS "bool OPAMP_SETUP_s::output = true"

.PP
Definition at line \fB118\fP of file \fBmln_opamp\&.h\fP\&.
.SS "\fBOPA_SETUP::MUXNEG_IN_t\fP OPAMP_SETUP_s::pin_neg = \fBOPA_SETUP::MUXNEG_INN\fP"

.PP
Definition at line \fB115\fP of file \fBmln_opamp\&.h\fP\&.
.SS "\fBOPA_SETUP::MUXPOS_IN_t\fP OPAMP_SETUP_s::pin_pos = \fBOPA_SETUP::MUXPOS_INP\fP"

.PP
Definition at line \fB114\fP of file \fBmln_opamp\&.h\fP\&.
.SS "bool OPAMP_SETUP_s::run_in_standby = false"

.PP
Definition at line \fB117\fP of file \fBmln_opamp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
