.TH "PIN_t" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PIN_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mln_gpio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "volatile PORT_t * \fBport\fP"
.br
.ti -1c
.RI "uint8_t \fBpin_num\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB93\fP of file \fBmln_gpio\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t PIN_t::pin_num"

.PP
Definition at line \fB96\fP of file \fBmln_gpio\&.h\fP\&.
.SS "volatile PORT_t* PIN_t::port"

.PP
Definition at line \fB95\fP of file \fBmln_gpio\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
