.TH "mlnlib/mln/tester.h" 3 "Thu Apr 27 2023" "Version alpha" "mlnlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlnlib/mln/tester.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned \fBudfboLDF\fP (unsigned a, unsigned b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned udfboLDF (unsigned a, unsigned b)"

.PP
Definition at line \fB12\fP of file \fBtester\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlnlib from the source code\&.
